/**
 * HttpBrainAdapter — BrainPort implementation backed by the Brain REST API.
 *
 * Provides concrete implementations of `archivePostmortem` and `archiveLesson`
 * that delegate to `archiveKnowledge` with the reserved category + tag
 * conventions defined in the campaign orchestrator design (Phase 9).
 *
 *   - postmortem: category `vauban_postmortem`, tags `["postmortem", "campaign:<slug>", "outcome:<outcome>"]`
 *   - lesson:     category `vauban_lesson`,     tags `["lesson", ...applies_to]`
 *
 * Auth: OAuth 2.1 bearer token (BRAIN_TOKEN env var) or x-api-key
 * (BRAIN_API_KEY env var). At least one must be present.
 *
 * ─── V12 planes (working / episodic / claims) — sprint-895, ADR-ECO-114 ───
 *
 * Wire paths verified against the deployed Brain server (2026-07-06):
 * `brain-protocol/src/routes/index.ts` mounts, `working-memory.routes.ts`,
 * `episodic.routes.ts`, `schemas/working-memory.schema.ts`,
 * `schemas/episodic.schema.ts`, `types/index.ts`.
 *
 * - `working` (WorkingMemoryPort) — wired to `/api/memory/working/:agentId`
 *   (Redis-backed, wm.service.ts). REQUIRES `HttpBrainAdapterOptions.agentId`:
 *   the deployed WM REST surface keys every slot by an `:agentId` path
 *   segment that `WorkingMemoryPort.set/get/delete/list` do not themselves
 *   carry per-call (only `runId`/`key`). Feature-detected: omitted (left
 *   `undefined`) when `agentId` is not supplied, per the "no throw on a
 *   missing plane" contract.
 * - `episodic` (EpisodicMemoryPort) — wired to
 *   `/api/memory/episodic/:agentId/events` (Postgres-backed, em.service.ts).
 *   Every method carries its own `agentId` argument, so this plane is always
 *   wired. Two wire gaps, both handled honestly rather than silently:
 *     1. `metadata`/`artifacts`/`traceId` on `append()` have no field in
 *        `EpisodicAppendBodySchema` — dropped with a console.warn, never
 *        silently discarded.
 *     2. `queryByTrace()` cannot be implemented: the deployed schema/response
 *        type carries no `trace_id` column (verified against
 *        `types/index.ts` `EpisodicEvent` + `episodic.schema.ts`) — returns
 *        `[]` with a console.warn rather than fabricating a match.
 * - `claims` (ClaimPort) — wired to `POST /api/memory/claims` (assert) and
 *   `POST /api/memory/claims/query` (query), now that Brain ships a REST
 *   surface for it (brain-protocol commit `66af575b`,
 *   `src/routes/claims.routes.ts` + `src/schemas/claims.schema.ts`, verified
 *   2026-07-06). Always wired — like `episodic`, neither method needs the
 *   adapter-level `agentId` WM requires. Two wire gaps, both handled the same
 *   honest way as the WM/EM gaps above:
 *     1. `ClaimAssertOptions.agentId` IS sent — `ClaimAssertInputSchema` gained
 *        an optional `agentId` field (brain-protocol #101) that Brain persists
 *        to `knowledge_claims.model_id`, the same column `claim_query`'s
 *        `agentId` filter reads. REQUIRES a Brain deployed with #101 ; against
 *        an older `.strict()` schema, sending `agentId` would 400.
 *     2. `scope`/`ClaimAssertOptions.scope` has no wire field either
 *        (documented directly on `ports/brain.ts` `MemoryScope`: "an
 *        HTTP-backed ClaimPort should not send it to claim_assert until
 *        Brain ships that parameter") — not sent; the returned `Claim.scope`
 *        is the SDK-local governance value the caller asked for (default
 *        "private"), not an echo of a server-side field.
 *   Graceful degradation for older (pre-claims) Brain deployments: the plane
 *   is always present on `BrainPort` (never `undefined`) — a deployment that
 *   lacks the route surfaces as a typed `BrainUnavailableError` from
 *   `assert`/`query` (404/`no such route`), exactly like any other transport
 *   failure on this adapter; construction never throws.
 *
 * Governance (rules/knowledge/memory-planes.md, EU AI Act Art. 19):
 * - `episodic.append`/`record` always send `sourceAgentId: agentId` — every
 *   write through this agent-facing adapter is agent-generated, so Brain can
 *   apply the 180-day retention floor.
 * - `archiveKnowledge` sends `source_agent_id: entry.source_agent_id ?? agentId`
 *   (verified against the deployed `/api/knowledge` — `CreateKnowledgeSchema`
 *   accepts `source_agent_id`, `knowledge.service.ts` persists it, brain-protocol
 *   PR #102). Same "agent-generated by default" convention as episodic; every
 *   runtime agent constructed with an adapter-level `agentId` (Forge, Bastion,
 *   Vauban Finance, Command Center) becomes attributable in the Cortex
 *   AgentStrip with zero call-site changes. Per-call `entry.source_agent_id`
 *   overrides when a caller needs to attribute to a different agent.
 * - `scope`/`memory_class` governance tags have no wire field yet on
 *   working/episodic (verified: neither schema declares one) — not
 *   fabricated here; this mirrors `ClaimPort`'s own documented
 *   deployed-vs-normative gap (`ports/brain.ts` `MemoryScope` doc).
 * - No PII-scrubbing pipeline lives in this adapter; callers must mask PII
 *   before calling `working`/`episodic`/`claims` per `knowledge/brain-archival.md`.
 */

import {
  type BrainEntry,
  type BrainEntryInput,
  type BrainPort,
  type BrainQueryFilters,
  BrainUnavailableError,
  type Claim,
  type ClaimAssertOptions,
  type ClaimPort,
  type ClaimQueryFilter,
  type EpisodicEvent,
  type EpisodicMemoryEntry,
  type EpisodicMemoryPort,
  type EpisodicQueryFilter,
  type LessonInput,
  MemoryValidationError,
  type PostmortemInput,
  type WorkingMemoryPort,
  type WorkingMemorySlot,
} from "../ports/brain.js";

/** @public */
export interface HttpBrainAdapterOptions {
  /** Brain REST API base URL (e.g. https://brain.api.vauban.tech). */
  baseUrl: string;
  /** Brain instance UUID. */
  brainId: string;
  /** OAuth 2.1 bearer token. Takes precedence over apiKey. */
  token?: string;
  /** x-api-key fallback (legacy). */
  apiKey?: string;
  /** Request timeout in milliseconds (default: 10 000). */
  timeoutMs?: number;
  /**
   * Identity of the agent this adapter instance acts as. Required to wire
   * the `working` (Working Memory) plane — see the module doc above for why
   * the WM REST surface needs it but `WorkingMemoryPort` doesn't carry it
   * per-call. Omit to skip wiring `working` (feature-detected absent).
   */
  agentId?: string;
  /**
   * Sink for this adapter's internal warnings (transport failures, degraded
   * responses, unsupported-field drops). Defaults to `console.warn` —
   * preserves the historical behavior for server-side hosts (Forge, Bastion,
   * Vauban Finance, the OODA factory) that expect these on stderr. A host
   * with an interactive terminal surface (the preste CLI) should inject a
   * quiet or debug-gated sink instead: an un-routed `console.warn` can land
   * mid-redraw of a live TUI region and corrupt it (see
   * `standalone-provider-router.ts`'s `PRESTE_DEBUG_TOOL_ARGS` precedent, and
   * `command-center:sprint-1067:t3-brain-http-noise`).
   */
  logger?: (message: string, ...args: unknown[]) => void;
  /**
   * Make `queryKnowledge` THROW `BrainUnavailableError` when the Brain did not
   * answer (transport failure, non-2xx, or `success:false`), instead of
   * returning `[]`. Default `false` ; every existing caller keeps the
   * historical fail-soft behaviour with no edit.
   *
   * Why it exists: fail-soft collapses "this Brain is down" and "this Brain
   * has nothing" into the same empty array. A single-Brain caller can live
   * with that; a fan-out cannot, because it would report a dead Brain as one
   * that answered with no results, and its "some Brain was unreachable" signal
   * would be a field that can never be populated. `createMultiBrainPortFromEnv`
   * sets this on every delegate for exactly that reason. An empty `data` array
   * from a Brain that DID answer is still a plain empty result, never a throw.
   */
  throwOnQueryFailure?: boolean;
}

interface BrainApiSingleResponse {
  success: boolean;
  data: {
    id: string;
    content: string;
    category?: string;
    tags?: string[];
    metadata?: Record<string, unknown>;
    created_at?: string;
  };
}

interface BrainApiListResponse {
  success: boolean;
  data: Array<{
    id: string;
    content: string;
    category?: string;
    tags?: string[];
    metadata?: Record<string, unknown>;
    created_at?: string;
  }>;
}

/** Working memory slot as returned by the deployed WM REST surface (wm.service.ts). */
interface WmSlotWire {
  slotId: string;
  content: unknown;
  importanceScore: number;
  pinned: boolean;
  createdAt: string;
}

/** Episodic event as returned by the deployed EM REST surface (em.service.ts / types/index.ts). */
interface EpisodicEventWire {
  id: string;
  session_id: string;
  agent_id: string;
  event_type: string;
  content: Record<string, unknown> | string;
  importance_score: number;
  source_agent_id: string | null;
  created_at: string;
}

/** `assertClaim` response (`AssertClaimResult` in brain-protocol `claims.service.ts`). */
interface ClaimAssertWire {
  id: string;
  created_at: string;
  entry_id: string;
}

/** A `knowledge_claims` row as returned by `queryClaims` (`KnowledgeClaim` in `types/index.ts`). */
interface ClaimWire {
  id: string;
  entry_id: string;
  subject: string;
  predicate: string;
  object: string | null;
  confidence: number;
  claim_source: "human_input" | "agent_inference" | "consolidation" | "external_ingestion";
  model_id: string | null;
  claim_status: "active" | "disputed" | "superseded" | "retracted";
  superseded_by: string | null;
  valid_from: string | null;
  valid_until: string | null;
  org_id: string;
  created_at: string;
  updated_at: string;
}

/** `POST /api/memory/claims/query` response body (`{claims, total}`). */
interface ClaimQueryWireResponse {
  claims: ClaimWire[];
  total: number;
}

interface WireResult<T> {
  ok: boolean;
  status: number;
  data?: T;
  error?: string;
}

/**
 * Create an HTTP-backed BrainPort.
 *
 * Includes concrete `archivePostmortem` and `archiveLesson` helpers that
 * delegate to `archiveKnowledge` with reserved categories / tag conventions.
 * @public
 */
export function createHttpBrainAdapter(opts: HttpBrainAdapterOptions): BrainPort {
  const {
    baseUrl,
    brainId,
    token,
    apiKey,
    timeoutMs = 10_000,
    agentId,
    throwOnQueryFailure = false,
  } = opts;
  const warn =
    opts.logger ?? ((message: string, ...args: unknown[]) => console.warn(message, ...args));

  const authHeaders: Record<string, string> = token
    ? { Authorization: `Bearer ${token}` }
    : apiKey
      ? { "x-api-key": apiKey }
      : {};

  /** Low-level fetch shared by both the legacy `request()` and `wireRequest()` paths. */
  async function doFetch(
    path: string,
    method: string,
    body?: unknown,
  ): Promise<{ res: Response | null; err?: Error }> {
    const controller = new AbortController();
    const timer = setTimeout(() => controller.abort(), timeoutMs);
    try {
      const res = await fetch(`${baseUrl}${path}`, {
        method,
        headers: { "Content-Type": "application/json", ...authHeaders },
        body: body !== undefined ? JSON.stringify(body) : undefined,
        signal: controller.signal,
      });
      return { res };
    } catch (err) {
      return { res: null, err: err as Error };
    } finally {
      clearTimeout(timer);
    }
  }

  async function request<T>(path: string, body?: unknown): Promise<T | null> {
    const method = body !== undefined ? "POST" : "GET";
    const { res, err } = await doFetch(path, method, body);
    if (err) {
      warn(`[brain-http] fetch error on ${path}:`, err.message);
      return null;
    }
    if (!res) return null;
    if (!res.ok) {
      warn(`[brain-http] ${res.status} on ${path}: ${await res.text().catch(() => "")}`);
      return null;
    }
    return (await res.json()) as T;
  }

  /**
   * The wire contract types `payload.error` as a string, but a `.strict()`
   * schema validation failure (e.g. Zod on a 400) can return a structured
   * object instead of a string. Template-interpolating that object directly
   * collapses to `"[object Object]"` and hides the real reason — JSON-serialize
   * non-string values so the logged/thrown message stays legible.
   */
  function stringifyWireError(error: unknown): string | undefined {
    if (error === undefined || error === null) return undefined;
    if (typeof error === "string") return error;
    try {
      return JSON.stringify(error);
    } catch {
      return String(error);
    }
  }

  /**
   * `{success, data, error}` envelope request with method + status
   * preserved — needed by the working/episodic planes to distinguish
   * "not found" (404) from a genuine transport failure.
   */
  async function wireRequest<T>(
    path: string,
    method: string,
    body?: unknown,
  ): Promise<WireResult<T>> {
    const { res, err } = await doFetch(path, method, body);
    if (err) {
      warn(`[brain-http] fetch error on ${method} ${path}:`, err.message);
      return { ok: false, status: 0, error: err.message };
    }
    if (!res) {
      return { ok: false, status: 0, error: "no response" };
    }
    let payload: { success?: boolean; data?: T; error?: unknown } | null = null;
    try {
      payload = (await res.json()) as { success?: boolean; data?: T; error?: unknown };
    } catch {
      payload = null;
    }
    if (!res.ok) {
      const errMsg = stringifyWireError(payload?.error) ?? `HTTP ${res.status}`;
      warn(`[brain-http] ${res.status} on ${method} ${path}: ${errMsg}`);
      return { ok: false, status: res.status, error: errMsg };
    }
    if (!payload || payload.success !== true) {
      return {
        ok: false,
        status: res.status,
        error: stringifyWireError(payload?.error) ?? "malformed response",
      };
    }
    return { ok: true, status: res.status, data: payload.data };
  }

  function mapEntry(raw: BrainApiSingleResponse["data"]): BrainEntry {
    return {
      id: raw.id,
      content: raw.content,
      category: raw.category,
      tags: raw.tags,
      metadata: raw.metadata,
      created_at: raw.created_at,
    };
  }

  function mapWmSlot(raw: WmSlotWire): WorkingMemorySlot {
    return {
      slotId: raw.slotId,
      content: raw.content,
      importanceScore: raw.importanceScore,
      pinned: raw.pinned,
      createdAt: raw.createdAt,
    };
  }

  function mapEpisodicEvent(raw: EpisodicEventWire): EpisodicEvent {
    return {
      id: raw.id,
      agentId: raw.agent_id,
      sessionId: raw.session_id,
      eventType: raw.event_type,
      content: raw.content,
      importanceScore: raw.importance_score,
      createdAt: raw.created_at,
      // artifacts/metadata: no such columns on the deployed EM surface.
    };
  }

  /**
   * `scope` has no wire field on the deployed claims surface (see module doc
   * + `ports/brain.ts` `MemoryScope`) — defaults to "private" per the
   * narrowest-scope discipline; a real per-claim scope would require a
   * Brain-side schema change.
   */
  function mapClaim(raw: ClaimWire): Claim {
    return {
      id: raw.id,
      subject: raw.subject,
      predicate: raw.predicate,
      object: raw.object ?? undefined,
      confidence: raw.confidence,
      claimSource: raw.claim_source,
      claimStatus: raw.claim_status,
      validFrom: raw.valid_from ?? undefined,
      validUntil: raw.valid_until ?? undefined,
      entryId: raw.entry_id,
      agentId: raw.model_id ?? undefined,
      createdAt: raw.created_at,
      scope: "private",
    };
  }

  /** Mirrors `episodicRowToLegacyEntry` (ports/brain.ts InMemoryEpisodicMemory). */
  function mapToLegacyEntry(ev: EpisodicEvent): EpisodicMemoryEntry {
    return {
      agentId: ev.agentId,
      runId: ev.sessionId,
      event: ev.eventType,
      metadata: typeof ev.content === "object" ? ev.content : undefined,
      timestamp: Date.parse(ev.createdAt),
    };
  }

  function buildWorkingMemoryPort(wmAgentId: string): WorkingMemoryPort {
    return {
      async set(runId, key, value, wopts) {
        if (wopts?.ttlMs !== undefined && wopts.ttlMs <= 0) {
          throw new MemoryValidationError("ttlMs must be a positive number of milliseconds");
        }
        // ttlMs has no wire field (WmSetBodySchema) — Brain's Redis TTL is
        // server-managed (docs/memory-contract-v12.md §2.4); validated above
        // for InMemoryWorkingMemory parity but not forwarded.
        const result = await wireRequest<WmSlotWire>(
          `/api/memory/working/${encodeURIComponent(wmAgentId)}`,
          "POST",
          {
            sessionId: runId,
            slotId: key,
            content: value,
            importanceScore: wopts?.importanceScore ?? 0.5,
            pinned: wopts?.pinned ?? false,
          },
        );
        if (!result.ok) {
          throw new BrainUnavailableError(
            `working_memory_set failed: ${result.error}`,
            result.status,
          );
        }
      },

      async get(runId, key) {
        const params = new URLSearchParams({ sessionId: runId });
        const result = await wireRequest<WmSlotWire>(
          `/api/memory/working/${encodeURIComponent(wmAgentId)}/${encodeURIComponent(key)}?${params.toString()}`,
          "GET",
        );
        if (!result.ok) {
          if (result.status === 404) return null;
          throw new BrainUnavailableError(
            `working_memory_get failed: ${result.error}`,
            result.status,
          );
        }
        return result.data?.content ?? null;
      },

      async delete(runId, key) {
        const params = new URLSearchParams({ sessionId: runId });
        const result = await wireRequest<{ deleted: boolean }>(
          `/api/memory/working/${encodeURIComponent(wmAgentId)}/${encodeURIComponent(key)}?${params.toString()}`,
          "DELETE",
        );
        if (!result.ok) {
          throw new BrainUnavailableError(
            `working_memory_delete failed: ${result.error}`,
            result.status,
          );
        }
      },

      async list(runId) {
        const params = new URLSearchParams({ sessionId: runId });
        const result = await wireRequest<WmSlotWire[]>(
          `/api/memory/working/${encodeURIComponent(wmAgentId)}?${params.toString()}`,
          "GET",
        );
        if (!result.ok) {
          throw new BrainUnavailableError(
            `working_memory_list failed: ${result.error}`,
            result.status,
          );
        }
        return (result.data ?? []).map(mapWmSlot);
      },
    };
  }

  function buildEpisodicMemoryPort(): EpisodicMemoryPort {
    async function append(
      evAgentId: string,
      sessionId: string,
      eventType: string,
      content: string | Record<string, unknown>,
      eopts?: {
        importanceScore?: number;
        artifacts?: string[];
        metadata?: Record<string, unknown>;
        traceId?: string;
      },
    ): Promise<string> {
      if (typeof content === "string" && content.trim().length === 0) {
        throw new MemoryValidationError("content must be a non-empty string or an object");
      }
      if (eopts?.metadata || eopts?.artifacts || eopts?.traceId) {
        warn(
          "[brain-http] episodic_append: metadata/artifacts/traceId are not supported by the " +
            "deployed Brain episodic REST surface (EpisodicAppendBodySchema has no such fields) — dropped, not sent.",
        );
      }
      const result = await wireRequest<EpisodicEventWire>(
        `/api/memory/episodic/${encodeURIComponent(evAgentId)}/events`,
        "POST",
        {
          sessionId,
          eventType,
          content,
          importanceScore: eopts?.importanceScore ?? 0.5,
          // Governance (ADR-ECO-114, EU AI Act Art. 19): every write through
          // this agent-facing adapter is agent-generated — mark the source
          // explicitly so Brain applies the 180-day retention floor.
          sourceAgentId: evAgentId,
        },
      );
      if (!result.ok || !result.data) {
        throw new BrainUnavailableError(`episodic_append failed: ${result.error}`, result.status);
      }
      return result.data.id;
    }

    async function record(
      evAgentId: string,
      runId: string,
      event: string,
      metadata?: Record<string, unknown>,
      ropts?: { traceId?: string },
    ): Promise<void> {
      // Delegates to append(), mirroring InMemoryEpisodicMemory's documented pattern.
      await append(evAgentId, runId, event, metadata ?? event, { traceId: ropts?.traceId });
    }

    async function query(filter: EpisodicQueryFilter): Promise<EpisodicEvent[]> {
      if (filter.agentId.trim().length === 0) {
        throw new MemoryValidationError("agentId is required");
      }
      const needsClientFilter =
        Boolean(filter.eventTypes?.length) || filter.minImportance !== undefined;
      const wantedLimit = filter.limit ?? 20;
      const params = new URLSearchParams();
      if (filter.sessionId) {
        params.set("session_id", filter.sessionId);
      } else if (filter.timerangeStart && filter.timerangeEnd) {
        params.set("from", filter.timerangeStart);
        params.set("to", filter.timerangeEnd);
      } else {
        // The deployed episodic REST surface requires session_id OR
        // (from AND to) — see EpisodicQueryParamsSchema; querying by
        // agentId alone (valid on InMemoryEpisodicMemory) has no direct
        // wire equivalent. Default to a wide window rather than throwing.
        const now = new Date();
        const ninetyDaysAgo = new Date(now.getTime() - 90 * 24 * 60 * 60 * 1000);
        params.set("from", ninetyDaysAgo.toISOString());
        params.set("to", now.toISOString());
      }
      params.set(
        "limit",
        String(Math.min(needsClientFilter ? wantedLimit * 3 : wantedLimit, 1000)),
      );

      const result = await wireRequest<EpisodicEventWire[]>(
        `/api/memory/episodic/${encodeURIComponent(filter.agentId)}/events?${params.toString()}`,
        "GET",
      );
      if (!result.ok) {
        throw new BrainUnavailableError(`episodic_query failed: ${result.error}`, result.status);
      }
      let events = (result.data ?? []).map(mapEpisodicEvent);
      // eventTypes / minImportance have no query param on the deployed
      // schema — applied client-side, best-effort.
      if (filter.eventTypes?.length) {
        const types = filter.eventTypes;
        events = events.filter((e) => types.includes(e.eventType));
      }
      if (filter.minImportance !== undefined) {
        const min = filter.minImportance;
        events = events.filter((e) => e.importanceScore >= min);
      }
      return events.slice(0, wantedLimit);
    }

    async function since(
      evAgentId: string,
      sinceMs: number,
      sopts?: { limit?: number },
    ): Promise<EpisodicMemoryEntry[]> {
      const events = await query({
        agentId: evAgentId,
        timerangeStart: new Date(sinceMs).toISOString(),
        timerangeEnd: new Date().toISOString(),
        limit: sopts?.limit ?? 20,
      });
      return events.map(mapToLegacyEntry).sort((a, b) => b.timestamp - a.timestamp);
    }

    async function queryByTrace(
      traceId: string,
      _opts?: { limit?: number },
    ): Promise<EpisodicMemoryEntry[]> {
      // Brain's deployed episodic REST/MCP surface does not persist
      // trace_id (verified: types/index.ts EpisodicEvent + schemas/
      // episodic.schema.ts carry no trace_id/traceId field) — return []
      // rather than fabricating a match. Known, documented gap; requires a
      // Brain-side schema change to close.
      warn(
        `[brain-http] queryByTrace("${traceId}"): trace correlation is not supported by the deployed Brain episodic surface — returning [].`,
      );
      return [];
    }

    return { append, record, since, queryByTrace, query };
  }

  function buildClaimsPort(): ClaimPort {
    async function assert(
      subject: string,
      predicate: string,
      object?: string,
      opts?: ClaimAssertOptions,
    ): Promise<string> {
      if (subject.trim().length === 0 || predicate.trim().length === 0) {
        throw new MemoryValidationError("subject and predicate are required");
      }
      // `agentId` IS accepted by the deployed claims REST surface (persisted to
      // knowledge_claims.model_id ; brain-protocol #101) — sent so an agent's
      // claims are retrievable by claim_query({agentId}). `scope` still has no
      // wire field (.strict()) — dropped with a warn until Brain ships it.
      if (opts?.scope !== undefined) {
        warn(
          "[brain-http] claim_assert: scope is not supported by the deployed Brain claims REST " +
            "surface (ClaimAssertInputSchema has no scope field, .strict()) — dropped, not sent.",
        );
      }
      const result = await wireRequest<ClaimAssertWire>("/api/memory/claims", "POST", {
        subject,
        predicate,
        object,
        claimSource: opts?.claimSource ?? "agent_inference",
        confidence: opts?.confidence ?? 0.8,
        validFrom: opts?.validFrom,
        validUntil: opts?.validUntil,
        entryId: opts?.entryId,
        agentId: opts?.agentId,
      });
      if (!result.ok || !result.data) {
        throw new BrainUnavailableError(`claim_assert failed: ${result.error}`, result.status);
      }
      return result.data.id;
    }

    async function query(filter: ClaimQueryFilter): Promise<Claim[]> {
      // agentId-only accepted since brain-protocol #103 (deployed 2026-07-10,
      // image 686f6df+): "everything this agent asserted" is a first-class query.
      if (!filter.subject && !filter.predicate && !filter.object && !filter.agentId) {
        throw new MemoryValidationError(
          "at least one of subject, predicate, object, or agentId must be provided",
        );
      }
      const result = await wireRequest<ClaimQueryWireResponse>("/api/memory/claims/query", "POST", {
        subject: filter.subject,
        predicate: filter.predicate,
        object: filter.object,
        claimStatus: filter.claimStatus ?? "active",
        agentId: filter.agentId,
        limit: filter.limit ?? 20,
      });
      if (!result.ok || !result.data) {
        throw new BrainUnavailableError(`claim_query failed: ${result.error}`, result.status);
      }
      return result.data.claims.map(mapClaim);
    }

    return { assert, query };
  }

  const adapter: BrainPort = {
    async archiveKnowledge(entry: BrainEntryInput): Promise<BrainEntry | null> {
      // `brain` names a DESTINATION among several, and this adapter is bound to
      // exactly one. Honouring it is impossible, ignoring it would file the
      // note in the wrong memory and still return "saved", so it is refused.
      // A `MultiBrainPort` strips the field before delegating, so a value
      // reaching here means the caller wired a single-Brain port and asked for
      // routing anyway.
      const { brain, ...wireEntry } = entry;
      if (brain !== undefined) {
        throw new MemoryValidationError(
          `this Brain adapter is bound to a single Brain and cannot route a write to "${brain}" ; use a MultiBrainPort`,
        );
      }
      const result = await request<BrainApiSingleResponse>("/api/knowledge", {
        ...wireEntry,
        brain_id: brainId,
        // Explicit per-call value wins; else the adapter-level agentId tags
        // the write automatically (mirrors episodic's sourceAgentId: agentId
        // convention above) — never fabricated when both are absent.
        source_agent_id: entry.source_agent_id ?? agentId,
      });
      if (!result?.success) return null;
      return mapEntry(result.data);
    },

    async queryKnowledge(query: string, filters?: BrainQueryFilters): Promise<BrainEntry[]> {
      const params = new URLSearchParams();
      params.set("q", query);
      params.set("brain_id", brainId);
      // UN SEUL TAG PART AU SERVEUR, LES SUIVANTS FILTRENT EN MEMOIRE.
      //
      // Le commentaire precedent justifiait cela par « l'API n'accepte qu'un
      // `tags` scalaire (Zod: string, pas array) ». C'est FAUX depuis que le
      // schema serveur declare
      // `tags: z.union([z.string(), z.array(z.string())])`
      // (brain-protocol, QueryKnowledgeSchema) : un parametre repete `tags` est
      // accepte et la route le lit via `c.req.queries("tags")`. Corrige le
      // 2026-08-30 apres lecture du schema ; une justification fausse est pire
      // qu'aucune, parce qu'elle empeche la prochaine lecture.
      //
      // LE COMPORTEMENT EST CONSERVE TEL QUEL, et c'est delibere : il est
      // CORRECT (les tags restants sont bien appliques, avec `limit * 3` pour
      // compenser), il est epingle par le test de parite de Forge, et le
      // changer toucherait le chemin de lecture Brain de tout le parc. Envoyer
      // tous les tags au serveur serait plus efficace, pas plus juste :
      // arbitrage founder, pas correction de nuit.
      const extraTags = filters?.tags?.slice(1) ?? [];
      if (filters?.tags?.length) params.set("tags", filters.tags[0]);
      if (filters?.limit) params.set("limit", String(Math.min(filters.limit * 3, 100)));

      const result = await request<BrainApiListResponse>(`/api/knowledge?${params.toString()}`);
      if (!result?.success) {
        // "Did not answer" and "answered with nothing" are the same empty
        // array to a fail-soft caller. Opt-in, so a fan-out can tell them
        // apart; see `throwOnQueryFailure`. The credential is never in this
        // message, only the host that failed.
        if (throwOnQueryFailure) {
          throw new BrainUnavailableError(`knowledge query failed against ${baseUrl}`);
        }
        return [];
      }
      return result.data
        .filter(
          (e) =>
            (!filters?.category || e.category === filters.category) &&
            extraTags.every((t) => e.tags?.includes(t)),
        )
        .map(mapEntry);
    },

    async archivePostmortem(input: PostmortemInput): Promise<void> {
      await adapter.archiveKnowledge({
        content: JSON.stringify(input, null, 2),
        category: "vauban_postmortem",
        tags: ["postmortem", `campaign:${input.campaign_slug}`, `outcome:${input.outcome}`],
      });
    },

    async archiveLesson(input: LessonInput): Promise<void> {
      await adapter.archiveKnowledge({
        content: JSON.stringify(input, null, 2),
        category: "vauban_lesson",
        tags: ["lesson", ...input.applies_to],
      });
    },

    // Feature-detected: WM requires an adapter-level agentId (see module doc).
    working: agentId ? buildWorkingMemoryPort(agentId) : undefined,
    // Always wired — every EpisodicMemoryPort method carries its own agentId.
    episodic: buildEpisodicMemoryPort(),
    // Always wired — neither assert() nor query() needs an adapter-level agentId.
    claims: buildClaimsPort(),
  };

  return adapter;
}

/**
 * Build an HTTP-backed {@link BrainPort} from the deployment env contract, or
 * `undefined` when Brain is not configured in this environment.
 *
 * Env contract (reuses this adapter's documented convention):
 *   - `BRAIN_URL`     — REST base URL. REQUIRED; absent → returns `undefined`
 *     (zero-regression: hosts/tests without Brain get no memory port).
 *   - `BRAIN_TOKEN`   — OAuth 2.1 bearer token (preferred).
 *   - `BRAIN_API_KEY` — `x-api-key` fallback when no `BRAIN_TOKEN`.
 *   - `BRAIN_ID`      — Brain instance UUID; only `archiveKnowledge` uses it,
 *     the `/api/memory/*` planes (WM/EM/Claims) ignore it, so it defaults to "".
 *
 * `agentId` keys the Working Memory plane (per-agent slot namespace); omit it to
 * skip WM wiring (Episodic + Claims are always wired). This is the helper
 * `createOODAAgent` uses to auto-wire every agent's `deps.memory` so the V12
 * Episodic + Claims planes receive runtime traffic (ADR-ECO-114).
 *
 * `logger` forwards to {@link HttpBrainAdapterOptions.logger} — omit it to
 * keep the default `console.warn` sink.
 * @public
 */
export function createBrainPortFromEnv(
  agentId?: string,
  logger?: (message: string, ...args: unknown[]) => void,
): BrainPort | undefined {
  const baseUrl = process.env.BRAIN_URL?.replace(/\/+$/, "");
  if (!baseUrl) return undefined;
  return createHttpBrainAdapter({
    baseUrl,
    brainId: process.env.BRAIN_ID ?? "",
    token: process.env.BRAIN_TOKEN,
    apiKey: process.env.BRAIN_API_KEY,
    agentId,
    logger,
  });
}
